import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Atta sentinel pattern — matches any file generated by Atta.
 * Covers all known markers: "Generated by Atta", "Generated by [Atta](...)",
 * "uses the Atta framework", etc.
 */
const ATTA_SENTINEL = /generated by.*atta|uses the atta framework/i;

/**
 * Init output files per adapter — where each tool's native init writes conventions.
 * Only Tier 1 (Claude Code, Copilot) and Tier 2 (Gemini) are parsed.
 * Tier 3 (Cursor, Codex) have no init output — skip silently.
 */
const INIT_FILES = {
  'claude-code': 'CLAUDE.md',
  copilot: join('.github', 'copilot-instructions.md'),
  gemini: 'GEMINI.md',
  // cursor, codex, github-action: no native init output to parse — returns null
};

/**
 * Parse existing init output from a tool's native init command.
 * Extracts build commands, test commands, and conventions as detection seeds.
 *
 * Seeds are advisory — Atta's own detection supplements rather than replaces them.
 * Returns null if no init output exists, the file is Atta-generated,
 * or parsing fails (graceful fallback).
 *
 * @param {string} targetDir - Project root directory
 * @param {string} adapter - Adapter name (e.g., 'claude-code', 'copilot', 'gemini')
 * @returns {{ source: string, buildCmd: string[], testCmd: string[], conventions: string[] } | null}
 */
export function parseInitOutput(targetDir, adapter) {
  const initFile = INIT_FILES[adapter];
  if (!initFile) return null; // Tier 3: no init output to parse

  const filePath = join(targetDir, initFile);
  if (!existsSync(filePath)) return null;

  let content;
  try {
    content = readFileSync(filePath, 'utf-8');
  } catch {
    return null; // Can't read — skip gracefully
  }

  // Skip if empty
  if (!content.trim()) return null;

  // Skip Atta-generated files (prevent feedback loops)
  if (ATTA_SENTINEL.test(content)) return null;

  // Parse the content for high-value signals
  const buildCmd = extractCommands(content, BUILD_PATTERNS);
  const testCmd = extractCommands(content, TEST_PATTERNS);
  const conventions = extractConventions(content);

  // Only return seeds if we found something useful
  if (buildCmd.length === 0 && testCmd.length === 0 && conventions.length === 0) {
    return null;
  }

  return {
    source: initFile,
    buildCmd,
    testCmd,
    conventions,
  };
}

// ─── Command Extraction ───────────────────────────────────────────────

/**
 * Patterns that indicate build commands.
 * Matches common package manager commands and build tool invocations.
 */
const BUILD_PATTERNS = [
  /npm run build/,
  /yarn build/,
  /pnpm (?:run )?build/,
  /make(?:\s+\w+)?$/,
  /cargo build/,
  /go build/,
  /gradle\s+build/,
  /mvn\s+(?:compile|package|install)/,
  /dotnet\s+build/,
  /pip install/,
  /poetry install/,
  /bundle install/,
  /cmake\s+/,
  /npx\s+(?:tsc|webpack|vite|esbuild|rollup|parcel|turbo)\b/,
];

/**
 * Patterns that indicate test commands.
 */
const TEST_PATTERNS = [
  /npm (?:run )?test/,
  /yarn test/,
  /pnpm (?:run )?test/,
  /node --test/,
  /\bjest\b/,
  /\bvitest\b/,
  /\bmocha\b/,
  /\bpytest\b/,
  /python -m (?:unittest|pytest)/,
  /cargo test/,
  /go test/,
  /gradle\s+test/,
  /mvn\s+test/,
  /dotnet\s+test/,
  /\brspec\b/,
  /bundle exec (?:rspec|rake test)/,
];

/**
 * Extract commands matching a set of patterns from markdown content.
 * Looks in code blocks (``` ... ```) and inline code (`...`).
 *
 * @param {string} content - Markdown content
 * @param {RegExp[]} patterns - Patterns to match against
 * @returns {string[]} Unique matched commands
 */
function extractCommands(content, patterns) {
  const commands = new Set();

  // Strip fenced code blocks from content before inline scan (avoid spurious matches)
  const codeBlockRegex = /```[\s\S]*?```/g;
  let match;
  while ((match = codeBlockRegex.exec(content)) !== null) {
    const block = match[0];
    for (const line of block.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed === '```' || trimmed.startsWith('```')) continue;
      for (const pattern of patterns) {
        if (pattern.test(trimmed)) {
          commands.add(trimmed);
          break;
        }
      }
    }
  }

  // Extract from inline code (backtick-wrapped) — exclude fenced blocks first
  const contentWithoutBlocks = content.replace(codeBlockRegex, '');
  const inlineCodeRegex = /`([^`]+)`/g;
  while ((match = inlineCodeRegex.exec(contentWithoutBlocks)) !== null) {
    const code = match[1].trim();
    for (const pattern of patterns) {
      if (pattern.test(code)) {
        commands.add(code);
        break;
      }
    }
  }

  return [...commands];
}

// ─── Convention Extraction ────────────────────────────────────────────

/**
 * Section headers that typically contain coding conventions.
 */
const CONVENTION_HEADERS = [
  /^#+\s*(?:coding\s+)?(?:conventions?|standards?|style\s*guide)/i,
  /^#+\s*(?:naming\s+)?conventions?/i,
  /^#+\s*(?:code|coding)\s+style/i,
  /^#+\s*(?:project\s+)?(?:rules|guidelines)/i,
  /^#+\s*(?:best\s+)?practices/i,
  /^#+\s*(?:architecture|patterns)\s+(?:conventions?|standards?|guidelines?|rules)/i,
];

/**
 * Extract convention bullet points from sections with convention-related headers.
 * Reads bullet points (- or *) under matching section headers until the next header.
 *
 * @param {string} content - Markdown content
 * @returns {string[]} Convention descriptions
 */
function extractConventions(content) {
  const conventions = [];
  const lines = content.split('\n');
  let inConventionSection = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Check if this is a header
    if (trimmed.startsWith('#')) {
      // Check if it's a convention-related header
      inConventionSection = CONVENTION_HEADERS.some((pattern) => pattern.test(trimmed));
      continue;
    }

    // Collect bullet points and numbered items within convention sections
    if (inConventionSection && /^(?:[-*]|\d+[.)])\s+/.test(trimmed)) {
      const text = trimmed.replace(/^(?:[-*]|\d+[.)])\s+/, '').trim();
      if (text.length > 5 && text.length < 300) { // Skip too-short or too-long entries
        conventions.push(text);
      }
    }
  }

  return conventions;
}
