#!/bin/bash
# check-init-parser.sh
# Verifies init-parser correctly extracts seeds from native init output
# and gracefully handles edge cases (empty, Atta-generated, malformed)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

ERRORS=0

run_test() {
  local name="$1"
  local adapter="$2"
  local expected="$3" # "null" or "seeds"
  local result
  local rc=0

  set +e
  result=$(node --input-type=module <<JSEOF
import { parseInitOutput } from '$REPO_ROOT/src/lib/init-parser.js';
const seeds = parseInitOutput('$WORK_DIR', '$adapter');
if (seeds === null) {
  console.log('null');
} else {
  console.log(JSON.stringify(seeds));
}
JSEOF
  )
  rc=$?
  set -e

  if [ "$rc" -ne 0 ]; then
    echo "FAIL: $name — script error (exit code $rc)"
    ERRORS=$((ERRORS + 1))
    return
  fi

  if [ "$expected" = "null" ]; then
    if [ "$result" = "null" ]; then
      echo "PASS: $name"
    else
      echo "FAIL: $name — expected null, got: $result"
      ERRORS=$((ERRORS + 1))
    fi
  else
    if [ "$result" = "null" ]; then
      echo "FAIL: $name — expected seeds, got null"
      ERRORS=$((ERRORS + 1))
    else
      echo "PASS: $name — $result"
    fi
  fi
}

# ─── Test 1: No init file → null ──────────────────────────────────────
run_test "no-init-file" "claude-code" "null"

# ─── Test 2: Empty file → null ────────────────────────────────────────
touch "$WORK_DIR/CLAUDE.md"
run_test "empty-file" "claude-code" "null"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 3: Atta-generated file → null (sentinel detection) ─────────
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# CLAUDE.md — Atta Agent Context

> Auto-loaded by Claude Code. Generated by [Atta](https://github.com/codelaude/atta).

## Build & Commands

```
npm run build
npm test
```
EOF
run_test "atta-generated-sentinel" "claude-code" "null"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 4: Valid init output with build/test commands → seeds ───────
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# My Project

## Build

```
npm run build
```

## Testing

```
npm test
jest --coverage
```

## Conventions

- Use camelCase for variables
- All components must have tests
- Prefer async/await over callbacks
EOF
run_test "valid-init-output" "claude-code" "seeds"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 5: Copilot adapter → parses copilot-instructions.md ────────
mkdir -p "$WORK_DIR/.github"
cat > "$WORK_DIR/.github/copilot-instructions.md" <<'EOF'
# Project Guidelines

## Standards

- Use TypeScript strict mode
- All API endpoints need validation

## Build

```
yarn build
```
EOF
run_test "copilot-init-output" "copilot" "seeds"
rm -rf "$WORK_DIR/.github"

# ─── Test 6: Tier 3 adapter (cursor) → null ──────────────────────────
run_test "tier3-cursor" "cursor" "null"

# ─── Test 7: Tier 3 adapter (codex) → null ───────────────────────────
run_test "tier3-codex" "codex" "null"

# ─── Test 8: github-action → null ────────────────────────────────────
run_test "github-action" "github-action" "null"

# ─── Test 9: File with no extractable commands or conventions → null ──
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# My Project

This is a project about widgets. It has many files.
We like to keep things simple.
EOF
run_test "no-extractable-content" "claude-code" "null"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 10: Atta sentinel variant "uses the Atta framework" → null ─
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# CLAUDE.md

This project uses the Atta framework for AI-assisted development.

## Build

```
npm run build
```
EOF
run_test "atta-sentinel-variant" "claude-code" "null"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 11: Gemini adapter with GEMINI.md → seeds ──────────────────
cat > "$WORK_DIR/GEMINI.md" <<'EOF'
# Project Context

## Conventions

- Follow PEP 8 for Python code
- Use type hints everywhere

## Testing

```
pytest
```
EOF
run_test "gemini-init-output" "gemini" "seeds"
rm "$WORK_DIR/GEMINI.md"

# ─── Test 12: Word boundary — "jest" in prose should not match ────────
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# Notes

We considered jest but decided against it.
The majesty of this codebase speaks for itself.

## Conventions

- Use vitest for all tests
EOF
run_test "word-boundary-jest" "claude-code" "seeds"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 13: Numbered convention list should be extracted ────────────
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# Project

## Coding Standards

1. Use camelCase for variables
2. All functions must have JSDoc
3. No default exports
EOF
run_test "numbered-conventions" "claude-code" "seeds"
rm "$WORK_DIR/CLAUDE.md"

# ─── Test 14: "Architecture" alone should NOT match conventions ───────
cat > "$WORK_DIR/CLAUDE.md" <<'EOF'
# Project

## Architecture

- API lives in src/api
- Frontend lives in src/ui
- Database models in src/models
EOF
run_test "architecture-not-convention" "claude-code" "null"
rm "$WORK_DIR/CLAUDE.md"

# ─── Results ──────────────────────────────────────────────────────────
echo ""
if [ "$ERRORS" -gt 0 ]; then
  echo "FAILED: $ERRORS test(s) failed"
  exit 1
else
  echo "ALL TESTS PASSED"
fi
