import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseFrontmatter, listSkills } from './claude-code.js';

/**
 * Generate AGENTS.md content from framework source.
 * Used by Copilot, Codex, Cursor, and Aider adapters.
 */
export function generateAgentsMd(frameworkRoot) {
  const skills = listSkills(frameworkRoot);
  const agents = listAgents(frameworkRoot);
  const version = readVersion(frameworkRoot);

  const lines = [];

  // Header
  lines.push('# AGENTS.md');
  lines.push('');
  lines.push(
    '> Generated by [Atta](https://github.com/codelaude/atta) — AI Dev Team Agent'
  );
  lines.push('');

  // Project Overview
  lines.push('## Project Overview');
  lines.push('');
  lines.push(
    'This project uses the Atta framework for AI-assisted development. Atta provides a virtual development team with specialized agents that guide code quality, architecture, and security.'
  );
  lines.push('');

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  lines.push('Atta uses a three-tier agent hierarchy:');
  lines.push('');
  lines.push(
    '1. **Core Agents** — Universal, always available (project-owner, librarian, rubber-duck, code-reviewer)'
  );
  lines.push(
    '2. **Coordinators** — Generated per project (fe-team-lead, be-team-lead)'
  );
  lines.push(
    '3. **Specialists** — Generated based on detected technologies'
  );
  lines.push('');

  // Agents section
  if (agents.length > 0) {
    lines.push('## Agents');
    lines.push('');
    lines.push('| Agent | Role | File |');
    lines.push('|-------|------|------|');
    for (const agent of agents) {
      lines.push(`| ${agent.name} | ${agent.role} | \`${agent.path}\` |`);
    }
    lines.push('');
  }

  // Skills / Commands
  if (skills.length > 0) {
    lines.push('## Build & Commands');
    lines.push('');
    lines.push('Available slash commands (skills):');
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    for (const skill of skills) {
      lines.push(`| \`/${skill.name}\` | ${skill.description} |`);
    }
    lines.push('');
  }

  // Code Style
  lines.push('## Code Style');
  lines.push('');
  lines.push(
    'Use `/review` for comprehensive code review or `/lint` for quick pattern checks. These skills enforce project-specific conventions detected from your tech stack.'
  );
  lines.push('');

  // Key Principles
  lines.push('## Key Principles');
  lines.push('');
  lines.push('- Agents guide, they don\'t auto-generate code');
  lines.push('- Each agent has explicit boundaries and constraints');
  lines.push('- Conflicts between agents escalate to the user');
  lines.push('- Knowledge is persistent via the Librarian agent');
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Atta v${version} — Run \`/atta\` in Claude Code to generate agents tailored to your tech stack.*`);
  lines.push('');

  return lines.join('\n');
}

function listAgents(frameworkRoot) {
  const agentsDir = join(frameworkRoot, 'agents');
  if (!existsSync(agentsDir)) return [];

  const agents = [];

  // Core agents (root .md files, skip INDEX and README)
  const rootFiles = readdirSync(agentsDir).filter(
    (f) => f.endsWith('.md') && f !== 'INDEX.md' && f !== 'README.md'
  );
  for (const file of rootFiles) {
    const name = file.replace('.md', '');
    agents.push({
      name: formatAgentName(name),
      role: 'Core Agent',
      path: `.claude/agents/${file}`,
    });
  }

  // Coordinators (skip legacy, generated, memory dirs)
  const coordDir = join(agentsDir, 'coordinators');
  if (existsSync(coordDir)) {
    const coordFiles = readdirSync(coordDir).filter((f) => f.endsWith('.md') && f !== 'README.md');
    for (const file of coordFiles) {
      const name = file.replace('.md', '');
      agents.push({
        name: formatAgentName(name),
        role: 'Coordinator',
        path: `.claude/agents/coordinators/${file}`,
      });
    }
  }

  // Specialists
  const specDir = join(agentsDir, 'specialists');
  if (existsSync(specDir)) {
    const specFiles = readdirSync(specDir).filter((f) => f.endsWith('.md') && f !== 'README.md');
    for (const file of specFiles) {
      const name = file.replace('.md', '');
      agents.push({
        name: formatAgentName(name),
        role: 'Specialist',
        path: `.claude/agents/specialists/${file}`,
      });
    }
  }

  return agents;
}

function formatAgentName(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function readVersion(frameworkRoot) {
  try {
    return readFileSync(
      join(frameworkRoot, '.metadata', 'version'),
      'utf-8'
    ).trim();
  } catch {
    return '0.0.0';
  }
}
