import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseFrontmatter, listSkills } from './claude-code.js';
import { readVersion } from '../lib/fs-utils.js';

/**
 * Generate AGENTS.md content from framework source.
 * Used by all adapters (Claude Code, Copilot, Codex, Gemini, Cursor).
 *
 * @param {string} claudeRoot - Path to .claude/ source (skills, agents)
 * @param {string} attaRoot - Path to .atta/ source (metadata with version)
 * @param {object} [options] - Adapter-specific options
 * @param {string} [options.skillPrefix='/'] - Prefix for skill invocation (e.g., '/' or '$')
 * @param {string} [options.agentBasePath='.claude/agents'] - Base path for agent files in output
 */
export function generateAgentsMd(claudeRoot, attaRoot, options = {}) {
  const { skillPrefix = '/', agentBasePath = '.claude/agents' } = options;
  const skills = listSkills(claudeRoot);
  const agents = listAgents(claudeRoot, agentBasePath);
  const version = readVersion(attaRoot);

  const lines = [];

  // Header
  lines.push('# AGENTS.md');
  lines.push('');
  lines.push(
    '> Generated by [Atta](https://github.com/codelaude/atta) — AI Dev Team Agent'
  );
  lines.push('');

  // Project Overview
  lines.push('## Project Overview');
  lines.push('');
  lines.push(
    'This project uses the Atta framework for AI-assisted development. Atta provides a virtual development team with specialized agents that guide code quality, architecture, and security.'
  );
  lines.push('');

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  lines.push('Atta uses a three-tier agent hierarchy:');
  lines.push('');
  lines.push(
    '1. **Core Agents** — Universal, always available (project-owner, librarian, rubber-duck, code-reviewer)'
  );
  lines.push(
    '2. **Coordinators** — Generated per project (fe-team-lead, be-team-lead)'
  );
  lines.push(
    '3. **Specialists** — Generated based on detected technologies'
  );
  lines.push('');

  // Agents section
  if (agents.length > 0) {
    lines.push('## Agents');
    lines.push('');
    lines.push('| Agent | Role | File |');
    lines.push('|-------|------|------|');
    for (const agent of agents) {
      lines.push(`| ${agent.name} | ${agent.role} | \`${agent.path}\` |`);
    }
    lines.push('');
  }

  // Skills / Commands
  if (skills.length > 0) {
    lines.push('## Build & Commands');
    lines.push('');
    lines.push('Available commands (skills):');
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    for (const skill of skills) {
      lines.push(`| \`${skillPrefix}${skill.name}\` | ${skill.description} |`);
    }
    lines.push('');
  }

  // Code Style
  const reviewSkill = skills.find((s) => s.name === 'atta-review');
  const lintSkill = skills.find((s) => s.name === 'atta-lint');
  if (reviewSkill || lintSkill) {
    lines.push('## Code Style');
    lines.push('');
    if (reviewSkill && lintSkill) {
      lines.push(
        `Use \`${skillPrefix}${reviewSkill.name}\` for comprehensive code review or \`${skillPrefix}${lintSkill.name}\` for quick pattern checks. These skills enforce project-specific conventions detected from your tech stack.`
      );
    } else if (reviewSkill) {
      lines.push(
        `Use \`${skillPrefix}${reviewSkill.name}\` for comprehensive code review. It enforces project-specific conventions detected from your tech stack.`
      );
    } else {
      lines.push(
        `Use \`${skillPrefix}${lintSkill.name}\` for quick pattern checks against project-specific conventions detected from your tech stack.`
      );
    }
    lines.push('');
  }

  // Key Principles
  lines.push('## Key Principles');
  lines.push('');
  lines.push('- Agents guide, they don\'t auto-generate code');
  lines.push('- Each agent has explicit boundaries and constraints');
  lines.push('- Conflicts between agents escalate to the user');
  lines.push('- Knowledge is persistent via the Librarian agent');
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Atta v${version} — Run \`${skillPrefix}atta\` to generate agents tailored to your tech stack.*`);
  lines.push('');

  return lines.join('\n');
}

/**
 * List agent definitions from framework source.
 * @param {string} claudeRoot - Path to .claude/ source (agents live here)
 * @param {string} agentBasePath - Base path prefix for agent files in output
 */
function listAgents(claudeRoot, agentBasePath = '.claude/agents') {
  const agentsDir = join(claudeRoot, 'agents');
  if (!existsSync(agentsDir)) return [];

  const agents = [];

  // Core agents (root .md files, skip INDEX and README)
  const rootFiles = readdirSync(agentsDir).filter(
    (f) => f.endsWith('.md') && f !== 'INDEX.md' && f !== 'README.md'
  );
  for (const file of rootFiles) {
    const name = file.replace('.md', '');
    agents.push({
      name: formatAgentName(name),
      role: 'Core Agent',
      path: `${agentBasePath}/${file}`,
    });
  }

  // Coordinators (skip legacy, generated, memory dirs)
  const coordDir = join(agentsDir, 'coordinators');
  if (existsSync(coordDir)) {
    const coordFiles = readdirSync(coordDir).filter((f) => f.endsWith('.md') && f !== 'README.md');
    for (const file of coordFiles) {
      const name = file.replace('.md', '');
      agents.push({
        name: formatAgentName(name),
        role: 'Coordinator',
        path: `${agentBasePath}/coordinators/${file}`,
      });
    }
  }

  // Specialists
  const specDir = join(agentsDir, 'specialists');
  if (existsSync(specDir)) {
    const specFiles = readdirSync(specDir).filter((f) => f.endsWith('.md') && f !== 'README.md');
    for (const file of specFiles) {
      const name = file.replace('.md', '');
      agents.push({
        name: formatAgentName(name),
        role: 'Specialist',
        path: `${agentBasePath}/specialists/${file}`,
      });
    }
  }

  return agents;
}

function formatAgentName(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
