import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';
import { listSkills } from './claude-code.js';
import { generateAgentsMd } from './agents-md.js';
import { copyAgentFiles, copyBootstrap, copySharedContent, rewriteSkillBody, createMemoryDirectory, listAgentDefs } from './shared.js';
import { generateReviewRules, formatCodex } from './review-guidance.js';

/**
 * Codex CLI adapter — generates .agents/skills/, .agents/agents/, and AGENTS.md.
 *
 * Codex CLI reads AGENTS.md as the primary instruction file.
 * Skills are placed at .agents/skills/{name}/SKILL.md.
 * Agent definitions are placed at .agents/agents/{name}.md.
 * Skill activation via /skills menu or $skill-name mention.
 */
export function install(claudeRoot, attaRoot, targetDir, options = {}) {
  const results = { files: 0 };

  // Generate AGENTS.md with Codex-specific paths and $ prefix
  const agentsMd = generateAgentsMd(claudeRoot, attaRoot, {
    skillPrefix: '$',
    agentBasePath: '.agents/agents',
  });
  writeFileSync(join(targetDir, 'AGENTS.md'), agentsMd);
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} AGENTS.md`);
  }

  // Codex uses $skill invocation — rewrite /command → $command (used by both skills and agents)
  const codexCommandMap = {
    review: '$review',
    agent: '$agent',
    atta: '$atta',
    preflight: '$preflight',
    lint: '$lint',
    test: '$test',
    collaborate: '$collaborate',
    'team-lead': '$team-lead',
    librarian: '$librarian',
    patterns: '$patterns',
    profile: '$profile',
    'security-audit': '$security-audit',
    ship: '$ship',
    tutorial: '$tutorial',
    optimize: '$optimize',
    update: '$update',
    migrate: '$migrate',
  };

  // Copy skills to .agents/skills/
  const skillsDir = join(claudeRoot, 'skills');
  if (existsSync(skillsDir)) {
    const skills = listSkills(claudeRoot);
    const agentsSkillsDir = join(targetDir, '.agents', 'skills');

    const rewriteConfig = {
      agentsPath: '.agents/agents',
      memoryPath: '.agents/agents/memory',
      commandMap: codexCommandMap,
    };

    for (const skill of skills) {
      const src = join(skillsDir, skill.dirName, 'SKILL.md');
      const dest = join(agentsSkillsDir, skill.dirName, 'SKILL.md');

      if (!existsSync(src)) continue;

      mkdirSync(join(agentsSkillsDir, skill.dirName), { recursive: true });

      // Rewrite body content for Codex compatibility
      const content = readFileSync(src, 'utf-8');
      const fmMatch = content.match(/^---\n[\s\S]*?\n---\n/);
      if (fmMatch) {
        const frontmatter = fmMatch[0];
        const body = content.slice(frontmatter.length);
        writeFileSync(dest, frontmatter + rewriteSkillBody(body, rewriteConfig));
      } else {
        writeFileSync(dest, rewriteSkillBody(content, rewriteConfig));
      }

      results.files++;
    }

    if (!options.quiet) {
      console.log(
        `  ${pc.green('✓')} .agents/skills/ (${skills.length} skills)`
      );
    }
  }

  // Copy agent definitions to .agents/agents/ (rewrite body for Codex paths)
  const codexAgentRewriteConfig = {
    agentsPath: '.agents/agents',
    memoryPath: '.agents/agents/memory',
    commandMap: codexCommandMap,
  };

  const agentCount = copyAgentFiles(
    claudeRoot,
    join(targetDir, '.agents', 'agents'),
    {
      ...options,
      transformFrontmatter: (fm) => ({
        name: fm.name,
        description: fm.description,
      }),
      transformBody: (body) => rewriteSkillBody(body, codexAgentRewriteConfig),
    }
  );
  results.files += agentCount;

  if (!options.quiet && agentCount > 0) {
    console.log(
      `  ${pc.green('✓')} .agents/agents/ (${agentCount} agent definitions)`
    );
  }

  // Generate .codex/config.toml with [agents.*] sections
  const agentDefs = listAgentDefs(claudeRoot);
  if (agentDefs.length > 0) {
    const codexDir = join(targetDir, '.codex');
    mkdirSync(codexDir, { recursive: true });

    const tomlLines = [
      '# Atta Agent Definitions',
      '# Generated by Atta framework — do not edit manually.',
      '# See .agents/agents/ for full agent instructions.',
      '',
    ];

    for (const agent of agentDefs) {
      const desc = (agent.description || `Atta ${agent.name} agent`)
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t')
        .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g,
          (ch) => '\\u' + ch.charCodeAt(0).toString(16).padStart(4, '0'));
      // Quote the key to handle names with dots, spaces, or other non-bare-key chars
      const safeKey = /^[A-Za-z0-9_-]+$/.test(agent.name) ? agent.name : `"${agent.name.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
      tomlLines.push(`[agents.${safeKey}]`);
      tomlLines.push(`description = "${desc}"`);
      tomlLines.push(`config_file = ".agents/agents/${agent.fileName}"`);
      tomlLines.push('');
    }

    const configPath = join(codexDir, 'config.toml');
    writeFileSync(configPath, tomlLines.join('\n'));
    results.files++;

    if (!options.quiet) {
      console.log(
        `  ${pc.green('✓')} .codex/config.toml (${agentDefs.length} agent sections)`
      );
    }
  }

  // Create memory directory with directives placeholder
  createMemoryDirectory(join(targetDir, '.agents', 'agents'), options);
  results.files++;

  // Append review guidelines to AGENTS.md (idempotent — replace if already present)
  const reviewRules = generateReviewRules(attaRoot, options.detectedTechs);
  const reviewSection = formatCodex(reviewRules);
  const agentsMdPath = join(targetDir, 'AGENTS.md');
  let existingAgentsMd = readFileSync(agentsMdPath, 'utf-8');
  const sentinel = '## Review Guidelines';
  if (existingAgentsMd.includes(sentinel)) {
    existingAgentsMd = existingAgentsMd.slice(0, existingAgentsMd.indexOf(sentinel)).trimEnd() + '\n';
  }
  writeFileSync(agentsMdPath, existingAgentsMd + reviewSection);

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} AGENTS.md (appended review guidelines)`);
  }

  // Copy shared content to .atta/ (team, project, scripts, metadata)
  const sharedCount = copySharedContent(attaRoot, targetDir, options);
  results.files += sharedCount;

  // Copy bootstrap to .atta/bootstrap/
  const bootstrapCount = copyBootstrap(attaRoot, targetDir, options);
  results.files += bootstrapCount;

  return results;
}
