import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';
import { listSkills } from './claude-code.js';
import { generateAgentsMd } from './agents-md.js';
import { copyAgentFiles, copyBootstrap, copySharedContent, rewriteSkillBody, filterSkillFrontmatter, CODEX_SKILL_FIELDS, checkSkillConflicts, createMemoryDirectory, generateHooks } from './shared.js';
import { generateReviewRules, formatCodex } from './review-guidance.js';
import { generateRules, writeToolAgnosticRules, installCodexRules } from './rules-generator.js';

/**
 * Codex CLI adapter — generates .agents/skills/, .agents/agents/, AGENTS.md,
 * and a compatibility .codex/config.toml placeholder.
 *
 * Codex CLI reads AGENTS.md as the primary instruction file.
 * Skills are placed at .agents/skills/{name}/SKILL.md.
 * Agent definitions are placed at .agents/agents/{name}.md for Atta skills
 * such as $atta-agent. They are not registered as native Codex agent roles
 * until the config_file schema is verified for current Codex builds.
 * Skill activation via /skills menu or $skill-name mention.
 *
 * Skill frontmatter: Codex only reads name and description. All other fields
 * (disable-model-invocation, allowed-tools, argument-hint, etc.) are stripped.
 */

// CODEX_SKILL_FIELDS imported from shared.js (single source of truth)
export function install(claudeRoot, attaRoot, targetDir, options = {}) {
  const results = { files: 0 };
  const skills = listSkills(claudeRoot).filter((s) => s.userInvocable !== false);
  checkSkillConflicts(skills, 'codex', options);

  // Codex uses $skill invocation — build commandMap dynamically: /atta-review → $atta-review
  const codexCommandMap = Object.fromEntries(
    skills.map((s) => [s.dirName, `$${s.dirName}`])
  );
  const codexRewriteConfig = {
    agentsPath: '.agents/agents',
    memoryPath: '.agents/agents/memory',
    commandMap: codexCommandMap,
  };

  // Generate AGENTS.md with Codex-specific paths and $ prefix
  const agentsMd = generateAgentsMd(claudeRoot, attaRoot, {
    skillPrefix: '$',
    agentBasePath: '.agents/agents',
    selectedAgents: options.selectedAgents,
  });
  writeFileSync(join(targetDir, 'AGENTS.md'), agentsMd);
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} AGENTS.md`);
  }

  // Copy skills to .agents/skills/
  const skillsDir = join(claudeRoot, 'skills');
  if (existsSync(skillsDir)) {
    const agentsSkillsDir = join(targetDir, '.agents', 'skills');

    for (const skill of skills) {
      const src = join(skillsDir, skill.dirName, 'SKILL.md');
      const dest = join(agentsSkillsDir, skill.dirName, 'SKILL.md');

      if (!existsSync(src)) continue;

      mkdirSync(join(agentsSkillsDir, skill.dirName), { recursive: true });

      // Rewrite frontmatter (strip to name+description) and body for Codex compatibility
      const content = readFileSync(src, 'utf-8');
      const fmMatch = content.match(/^---\n[\s\S]*?\n---\n/);
      if (fmMatch) {
        const frontmatter = fmMatch[0];
        const body = content.slice(frontmatter.length);
        writeFileSync(dest, filterSkillFrontmatter(frontmatter, CODEX_SKILL_FIELDS) + rewriteSkillBody(body, codexRewriteConfig));
      } else {
        writeFileSync(dest, rewriteSkillBody(content, codexRewriteConfig));
      }

      results.files++;
    }

    if (!options.quiet) {
      console.log(
        `  ${pc.green('✓')} .agents/skills/ (${skills.length} skills)`
      );
    }
  }

  // Copy agent definitions to .agents/agents/ (rewrite body for Codex paths)
  const agentCount = copyAgentFiles(
    claudeRoot,
    join(targetDir, '.agents', 'agents'),
    {
      ...options,
      transformFrontmatter: (fm) => ({
        name: fm.name,
        description: fm.description,
      }),
      transformBody: (body) => rewriteSkillBody(body, codexRewriteConfig),
    }
  );
  results.files += agentCount;

  if (!options.quiet && agentCount > 0) {
    console.log(
      `  ${pc.green('✓')} .agents/agents/ (${agentCount} agent definitions)`
    );
  }

  // Replace stale Atta-generated role registrations with a safe placeholder.
  // Current Codex builds parse config_file targets as TOML agent role files, so
  // pointing them at Markdown agent prompts causes startup warnings.
  // Only overwrite if the file is Atta-generated or contains [agents.*] sections;
  // preserve user-managed config files.
  const codexDir = join(targetDir, '.codex');
  mkdirSync(codexDir, { recursive: true });
  const configPath = join(codexDir, 'config.toml');
  const attaPlaceholder = [
    '# Atta Codex configuration',
    '# Generated by Atta framework — do not edit manually.',
    '# Native [agents.*] registration is intentionally disabled.',
    '# Use AGENTS.md, .agents/skills/, and $atta-agent with .agents/agents/*.md.',
    '',
  ].join('\n');

  let shouldWrite = true;
  if (existsSync(configPath)) {
    const existing = readFileSync(configPath, 'utf-8');
    const isAttaGenerated = existing.includes('Generated by Atta framework')
      || existing.includes('# Atta Agent Definitions')
      || existing.includes('# Atta Codex configuration');
    const hasAgentSections = /^\[agents\./m.test(existing);
    shouldWrite = isAttaGenerated || hasAgentSections;
  }

  if (shouldWrite) {
    writeFileSync(configPath, attaPlaceholder);
    results.files++;
    if (!options.quiet) {
      console.log(`  ${pc.green('✓')} .codex/config.toml (compatibility placeholder)`);
    }
  }

  // Create memory directory with directives placeholder
  createMemoryDirectory(join(targetDir, '.agents', 'agents'), options);
  results.files++;

  // Append review guidelines to AGENTS.md (idempotent — replace if already present)
  const reviewRules = generateReviewRules(attaRoot, options.detectedTechs);
  const reviewSection = formatCodex(reviewRules);
  const agentsMdPath = join(targetDir, 'AGENTS.md');
  let existingAgentsMd = readFileSync(agentsMdPath, 'utf-8');
  const sentinel = '## Review Guidelines';
  if (existingAgentsMd.includes(sentinel)) {
    existingAgentsMd = existingAgentsMd.slice(0, existingAgentsMd.indexOf(sentinel)).trimEnd() + '\n';
  }
  writeFileSync(agentsMdPath, existingAgentsMd + reviewSection);

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} AGENTS.md (appended review guidelines)`);
  }

  // Generate path-scoped rules (appended to AGENTS.md + .atta/team/rules/)
  const rules = generateRules(attaRoot, options.detectedTechs);
  if (rules.length > 0) {
    const agnosticCount = writeToolAgnosticRules(targetDir, rules);
    const nativeCount = installCodexRules(targetDir, rules);
    results.files += agnosticCount;

    if (!options.quiet) {
      console.log(`  ${pc.green('✓')} .atta/team/rules/ (${agnosticCount} rule files)`);
      if (nativeCount > 0) {
        console.log(`  ${pc.green('✓')} AGENTS.md (appended coding rules)`);
      }
    }
  }

  // Always regenerate hooks.json — enforcement hooks may change on re-init
  const codexHooksDir = join(targetDir, '.codex');
  mkdirSync(codexHooksDir, { recursive: true });
  const codexHooksConfig = generateHooks('codex', options.detectedTechs);
  writeFileSync(join(codexHooksDir, 'hooks.json'), JSON.stringify(codexHooksConfig, null, 2) + '\n');
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} .codex/hooks.json (experimental hooks placeholder)`);
  }

  // Copy shared content to .atta/ (team, project, scripts, metadata)
  const sharedCount = copySharedContent(attaRoot, targetDir, options);
  results.files += sharedCount;

  // Copy bootstrap to .atta/bootstrap/
  const bootstrapCount = copyBootstrap(attaRoot, targetDir, options);
  results.files += bootstrapCount;

  return results;
}
