import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';
import { listSkills } from './claude-code.js';
import { generateAgentsMd } from './agents-md.js';
import { copyAgentFiles, copyBootstrap, copySharedContent } from './shared.js';

/**
 * Gemini CLI adapter — generates GEMINI.md, .gemini/commands/, and .gemini/agents/.
 *
 * Gemini CLI uses:
 * - GEMINI.md: context file loaded into the model (equivalent to AGENTS.md)
 * - .gemini/commands/*.toml: project-scoped slash commands
 * - .gemini/agents/*.md: agent definition files
 *
 * Skills are converted from SKILL.md → TOML command files.
 * Note: Gemini extensions are global-only (~/.gemini/extensions/),
 * so we don't generate gemini-extension.json at the project level.
 */
export function install(claudeRoot, attaRoot, targetDir, options = {}) {
  const results = { files: 0 };

  // Generate GEMINI.md (same content as AGENTS.md, adapted for Gemini context)
  const geminiMd = generateGeminiMd(claudeRoot, attaRoot);
  writeFileSync(join(targetDir, 'GEMINI.md'), geminiMd);
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} GEMINI.md`);
  }

  // Convert skills to TOML commands at .gemini/commands/
  const skillsDir = join(claudeRoot, 'skills');
  if (existsSync(skillsDir)) {
    const skills = listSkills(claudeRoot);
    const commandsDir = join(targetDir, '.gemini', 'commands');
    mkdirSync(commandsDir, { recursive: true });

    for (const skill of skills) {
      const skillFile = join(skillsDir, skill.dirName, 'SKILL.md');
      if (!existsSync(skillFile)) continue;

      const toml = skillToToml(skill, skillFile);
      writeFileSync(join(commandsDir, `${skill.dirName}.toml`), toml);
      results.files++;
    }

    if (!options.quiet) {
      console.log(
        `  ${pc.green('✓')} .gemini/commands/ (${skills.length} TOML commands)`
      );
    }
  }

  // Copy agent definitions to .gemini/agents/
  const agentCount = copyAgentFiles(
    claudeRoot,
    join(targetDir, '.gemini', 'agents'),
    options
  );
  results.files += agentCount;

  if (!options.quiet && agentCount > 0) {
    console.log(
      `  ${pc.green('✓')} .gemini/agents/ (${agentCount} agent definitions)`
    );
  }

  // Copy shared content to .atta/ (knowledge, scripts, docs, metadata, context)
  const sharedCount = copySharedContent(attaRoot, targetDir, options);
  results.files += sharedCount;

  // Copy bootstrap to .atta/bootstrap/
  const bootstrapCount = copyBootstrap(attaRoot, targetDir, options);
  results.files += bootstrapCount;

  return results;
}

/**
 * Convert a SKILL.md file into a Gemini TOML command.
 * Extracts the prompt content from the SKILL.md body (after frontmatter).
 */
function skillToToml(skill, skillFile) {
  const content = readFileSync(skillFile, 'utf-8');

  // Extract body after frontmatter
  const body = content.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();

  // Escape for TOML multi-line string (triple quotes)
  // Only need to escape literal triple-quotes and backslashes
  const escapedBody = body
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"\\"\\"');

  const desc = (skill.description || `Run the ${skill.name} skill`)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');

  const lines = [];
  lines.push(`description = "${desc}"`);
  lines.push('');
  lines.push(`prompt = """`);
  lines.push(escapedBody);
  lines.push('"""');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate GEMINI.md — context file for Gemini CLI.
 * Based on AGENTS.md content with Gemini-specific framing and paths.
 */
function generateGeminiMd(claudeRoot, attaRoot) {
  // Reuse the AGENTS.md generator with Gemini-specific paths
  const agentsMd = generateAgentsMd(claudeRoot, attaRoot, {
    skillPrefix: '/',
    agentBasePath: '.gemini/agents',
  });

  // Replace header for Gemini context
  return agentsMd
    .replace('# AGENTS.md', '# GEMINI.md — Atta Agent Context')
    .replace(
      '> Generated by [Atta](https://github.com/codelaude/atta) — AI Dev Team Agent',
      '> Context file for Gemini CLI. Generated by [Atta](https://github.com/codelaude/atta).\n>\n> This file is loaded automatically as project context. It provides your agent team context.'
    );
}

