import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';
import { listSkills } from './claude-code.js';
import { generateAgentsMd } from './agents-md.js';
import { readVersion } from '../lib/fs-utils.js';

/**
 * Gemini CLI adapter — generates gemini-extension.json, GEMINI.md, and TOML commands.
 *
 * Gemini CLI extensions use:
 * - gemini-extension.json: manifest with name, version, contextFileName
 * - GEMINI.md: context file loaded into the model (equivalent to AGENTS.md)
 * - commands/*.toml: slash commands with description + prompt fields
 *
 * Skills are converted from SKILL.md → TOML command files.
 */
export function install(frameworkRoot, targetDir, options = {}) {
  const results = { files: 0 };

  // Generate GEMINI.md (same content as AGENTS.md, adapted for Gemini context)
  const geminiMd = generateGeminiMd(frameworkRoot);
  writeFileSync(join(targetDir, 'GEMINI.md'), geminiMd);
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} GEMINI.md`);
  }

  // Generate gemini-extension.json manifest
  const version = readVersion(frameworkRoot);
  const manifest = {
    name: 'atta',
    version,
    contextFileName: 'GEMINI.md',
  };

  writeFileSync(
    join(targetDir, 'gemini-extension.json'),
    JSON.stringify(manifest, null, 2) + '\n'
  );
  results.files++;

  if (!options.quiet) {
    console.log(`  ${pc.green('✓')} gemini-extension.json`);
  }

  // Convert skills to TOML commands
  const skillsDir = join(frameworkRoot, 'skills');
  if (existsSync(skillsDir)) {
    const skills = listSkills(frameworkRoot);
    const commandsDir = join(targetDir, 'commands');
    mkdirSync(commandsDir, { recursive: true });

    for (const skill of skills) {
      const skillFile = join(skillsDir, skill.dirName, 'SKILL.md');
      if (!existsSync(skillFile)) continue;

      const toml = skillToToml(skill, skillFile);
      writeFileSync(join(commandsDir, `${skill.dirName}.toml`), toml);
      results.files++;
    }

    if (!options.quiet) {
      console.log(
        `  ${pc.green('✓')} commands/ (${skills.length} TOML commands)`
      );
    }
  }

  return results;
}

/**
 * Convert a SKILL.md file into a Gemini TOML command.
 * Extracts the prompt content from the SKILL.md body (after frontmatter).
 */
function skillToToml(skill, skillFile) {
  const content = readFileSync(skillFile, 'utf-8');

  // Extract body after frontmatter
  const body = content.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();

  // Escape for TOML multi-line string (triple quotes)
  // Only need to escape literal triple-quotes and backslashes
  const escapedBody = body
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"""');

  const desc = (skill.description || `Run the ${skill.name} skill`)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');

  const lines = [];
  lines.push(`description = "${desc}"`);
  lines.push('');
  lines.push(`prompt = """`);
  lines.push(escapedBody);
  lines.push('"""');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate GEMINI.md — context file for Gemini CLI.
 * Based on AGENTS.md content with Gemini-specific framing.
 */
function generateGeminiMd(frameworkRoot) {
  // Reuse the AGENTS.md generator and adapt the header
  const agentsMd = generateAgentsMd(frameworkRoot);

  // Replace header for Gemini context
  return agentsMd
    .replace('# AGENTS.md', '# GEMINI.md — Atta Agent Context')
    .replace(
      '> Generated by [Atta](https://github.com/codelaude/atta) — AI Dev Team Agent',
      '> Context file for Gemini CLI. Generated by [Atta](https://github.com/codelaude/atta).\n>\n> This file is loaded automatically by the Atta extension. It provides your agent team context.'
    );
}
